//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShipment.Information.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InformationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartShipment.Information.Properties.InformationResources", typeof(InformationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings or errors were received during data entry.
        ///This can be caused by incorrect data or the inability to insert data in automatic mode. Check inserted entries before proceeding..
        /// </summary>
        public static string _WARN_INCORRECT_DATA_AND_DIALOGS {
            get {
                return ResourceManager.GetString("_WARN_INCORRECT_DATA_AND_DIALOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acumatica Shipping Tool Integration.
        /// </summary>
        public static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screen \&quot;Shipment details \&quot; is not available. Make sure that the application is running and not blocked by pop-up windows or message dialogs..
        /// </summary>
        public static string ERROR_ADAPTER_SHIPMENT_SCREEN_IS_NOT_INTERACTIVE {
            get {
                return ResourceManager.GetString("ERROR_ADAPTER_SHIPMENT_SCREEN_IS_NOT_INTERACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatoin settings error: Can`t get access to application settings configuration directory..
        /// </summary>
        public static string ERROR_APPLICATION_SETTINGS_DIRECTORY_ACCESS {
            get {
                return ResourceManager.GetString("ERROR_APPLICATION_SETTINGS_DIRECTORY_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatoin settings error: Can`t get access to application settings file.
        /// </summary>
        public static string ERROR_APPLICATION_SETTINGS_FILE_ACCESS {
            get {
                return ResourceManager.GetString("ERROR_APPLICATION_SETTINGS_FILE_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatoin settings error: Can`t set and save application settings!.
        /// </summary>
        public static string ERROR_APPLICATION_SETTINGS_SET_OR_SAVE {
            get {
                return ResourceManager.GetString("ERROR_APPLICATION_SETTINGS_SET_OR_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatoin settings error: Can`t update application settings!.
        /// </summary>
        public static string ERROR_APPLICATION_SETTINGS_UPDATE {
            get {
                return ResourceManager.GetString("ERROR_APPLICATION_SETTINGS_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application stopped by error occurred.
        /// </summary>
        public static string ERROR_APPLICATION_STOPPED_BY_ERROR {
            get {
                return ResourceManager.GetString("ERROR_APPLICATION_STOPPED_BY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not connect to Acumatica. Check the site is available,  application Acumatica credentials settings, check local machine network available and try again..
        /// </summary>
        public static string ERROR_CANNOT_CONNECT_TO_ACUMATICA {
            get {
                return ResourceManager.GetString("ERROR_CANNOT_CONNECT_TO_ACUMATICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network parameters check is unsuccessful!
        ///    [{0}].
        /// </summary>
        public static string ERROR_CHECK_NETWORK_PARAMETERS {
            get {
                return ResourceManager.GetString("ERROR_CHECK_NETWORK_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error of create cache with type {0}.
        /// </summary>
        public static string ERROR_CREATE_APPLICATION_MAP_CACHE {
            get {
                return ResourceManager.GetString("ERROR_CREATE_APPLICATION_MAP_CACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value \&quot;Programm path\&quot; must be set before use shipment application..
        /// </summary>
        public static string ERROR_EXTERNAL_APPLICATION_PROCESS_NAME_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_EXTERNAL_APPLICATION_PROCESS_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active browser found..
        /// </summary>
        public static string ERROR_NO_ACTIVE_BROWSER_FOUND {
            get {
                return ResourceManager.GetString("ERROR_NO_ACTIVE_BROWSER_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shipment URL in active browsers found.
        /// </summary>
        public static string ERROR_NO_SHIPMENT_URI_FOUND {
            get {
                return ResourceManager.GetString("ERROR_NO_SHIPMENT_URI_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment(s) is not updated: .
        /// </summary>
        public static string ERROR_SHIPMENTS_IS_NOT_UPDATED {
            get {
                return ResourceManager.GetString("ERROR_SHIPMENTS_IS_NOT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment &lt;{0}&gt; cannot be updated:.
        /// </summary>
        public static string ERROR_SHIPMENTS_NUMBER_IS_NOT_UPDATED {
            get {
                return ResourceManager.GetString("ERROR_SHIPMENTS_NUMBER_IS_NOT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error of parse string {0} to URL..
        /// </summary>
        public static string ERROR_URI_STRING_PARSE {
            get {
                return ResourceManager.GetString("ERROR_URI_STRING_PARSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started.
        /// </summary>
        public static string INFO_APPLICATION_STARTED {
            get {
                return ResourceManager.GetString("INFO_APPLICATION_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application starting.
        /// </summary>
        public static string INFO_APPLICATION_STARTING {
            get {
                return ResourceManager.GetString("INFO_APPLICATION_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application stoped.
        /// </summary>
        public static string INFO_APPLICATION_STOPED {
            get {
                return ResourceManager.GetString("INFO_APPLICATION_STOPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network parameters check is successful!.
        /// </summary>
        public static string INFO_CHECK_NETWORK_PARAMETERS {
            get {
                return ResourceManager.GetString("INFO_CHECK_NETWORK_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Monitoring: Process export file {0}, processed row(s): {1}..
        /// </summary>
        public static string INFO_EXPORT_FILE_PROCESSED {
            get {
                return ResourceManager.GetString("INFO_EXPORT_FILE_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FedEx Ship Manager: filling in Shipment packages values completed.
        /// </summary>
        public static string INFO_FEDEX_FILL_PACKAGE_DATA {
            get {
                return ResourceManager.GetString("INFO_FEDEX_FILL_PACKAGE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FedEx Ship Manager: filling in Shipment values completed.
        /// </summary>
        public static string INFO_FEDEX_FILL_SHIPMENT_DATA {
            get {
                return ResourceManager.GetString("INFO_FEDEX_FILL_SHIPMENT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FedEx Ship Manager: initialization of map of controls completed.
        /// </summary>
        public static string INFO_FEDEX_INIT_CONTROL_MAP {
            get {
                return ResourceManager.GetString("INFO_FEDEX_INIT_CONTROL_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FedEx Ship Manager: start application.
        /// </summary>
        public static string INFO_FEDEX_START_APPLICATION {
            get {
                return ResourceManager.GetString("INFO_FEDEX_START_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FedEx Ship Manager: starting application.
        /// </summary>
        public static string INFO_FEDEX_STARTING_APPLICATION {
            get {
                return ResourceManager.GetString("INFO_FEDEX_STARTING_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings: Properties saved.
        /// </summary>
        public static string INFO_PROPERTIES_SAVED {
            get {
                return ResourceManager.GetString("INFO_PROPERTIES_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings: Property {0} changed, old value: {1}, new value {2}.
        /// </summary>
        public static string INFO_PROPERTY_VALUE_CHANGED {
            get {
                return ResourceManager.GetString("INFO_PROPERTY_VALUE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Shipment &lt;{0}&gt;, Packages count: {1}.
        /// </summary>
        public static string INFO_RECEIVED_SHIPMENT {
            get {
                return ResourceManager.GetString("INFO_RECEIVED_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Monitoring: Start monitoring export file {0}.
        /// </summary>
        public static string INFO_START_EXPORTFILE_MONITORING {
            get {
                return ResourceManager.GetString("INFO_START_EXPORTFILE_MONITORING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network provider: Successfully updated {0} Shippment(s): {1}.
        /// </summary>
        public static string INFO_SUCCESS_UPDATE_SHIPMENT {
            get {
                return ResourceManager.GetString("INFO_SUCCESS_UPDATE_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Worldship: filling in Shipment packages values completed.
        /// </summary>
        public static string INFO_UPS_FILL_PACKAGE_DATA {
            get {
                return ResourceManager.GetString("INFO_UPS_FILL_PACKAGE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Worldship: filling in Shipment values completed.
        /// </summary>
        public static string INFO_UPS_FILL_SHIPMENT_DATA {
            get {
                return ResourceManager.GetString("INFO_UPS_FILL_SHIPMENT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Worldship: initialization of map of controls completed.
        /// </summary>
        public static string INFO_UPS_INIT_CONTROL_MAP {
            get {
                return ResourceManager.GetString("INFO_UPS_INIT_CONTROL_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Worldship: start application.
        /// </summary>
        public static string INFO_UPS_START_APPLICATION {
            get {
                return ResourceManager.GetString("INFO_UPS_START_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Worldship: starting application.
        /// </summary>
        public static string INFO_UPS_STARTING_APPLICATION {
            get {
                return ResourceManager.GetString("INFO_UPS_STARTING_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit?.
        /// </summary>
        public static string MESSAGE_APPLICATION_EXIT {
            get {
                return ResourceManager.GetString("MESSAGE_APPLICATION_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you start, you need to set the necessary settings for running the application. Required parameters are marked with *. Fill in the setting values and click OK to continue..
        /// </summary>
        public static string MESSAGE_PARAMETERS_NEED_BE_INSTALLED {
            get {
                return ResourceManager.GetString("MESSAGE_PARAMETERS_NEED_BE_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters required for running the application are not installed. Continuation of work is impossible..
        /// </summary>
        public static string MESSAGE_PARAMETERS_NOT_INSTALLED {
            get {
                return ResourceManager.GetString("MESSAGE_PARAMETERS_NOT_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acumatica internal error. See log for more information..
        /// </summary>
        public static string Warn_Acumatica_Internal_Error_Message {
            get {
                return ResourceManager.GetString("Warn_Acumatica_Internal_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Shipment screen is not empty. Before load data from Acumatica and create new Shipment, you should process current shipment or Undo changes/Clear fields..
        /// </summary>
        public static string WARN_CURRENT_SHIPMENT_SCREEN_ISNOT_EMPTY {
            get {
                return ResourceManager.GetString("WARN_CURRENT_SHIPMENT_SCREEN_ISNOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials or URL string.
        /// </summary>
        public static string Warn_Invalid_credentials_or_URL_string {
            get {
                return ResourceManager.GetString("Warn_Invalid_credentials_or_URL_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process the Shipment &lt;{0}&gt;. FedEx Ship Manager should be running..
        /// </summary>
        public static string WARN_NO_PROCESS_FOUND_FOR_FEDEX_APPLICATION {
            get {
                return ResourceManager.GetString("WARN_NO_PROCESS_FOUND_FOR_FEDEX_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process the Shipment &lt;{0}&gt;. UPS WorldShip  should be running..
        /// </summary>
        public static string WARN_NO_PROCESS_FOUND_FOR_UPS_APPLICATION {
            get {
                return ResourceManager.GetString("WARN_NO_PROCESS_FOUND_FOR_UPS_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate the Acumatica Shipment screen. Please make sure that the Acumatica Shipment screen is active in one of the supported Web Browsers and a Shipment number is selected..
        /// </summary>
        public static string WARN_NO_WAY_TO_GET_SHIPMENT {
            get {
                return ResourceManager.GetString("WARN_NO_WAY_TO_GET_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate the Acumatica Shipment. Please make sure that the Acumatica Shipment screen is active in one of the supported Web Browsers and a Shipment number is selected.
        ///[ {0} ].
        /// </summary>
        public static string WARN_NO_WAY_TO_GET_SHIPMENT_EXTENDED {
            get {
                return ResourceManager.GetString("WARN_NO_WAY_TO_GET_SHIPMENT_EXTENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more required fields can not be filled: [{0}]. Check the availability of fields and shipment data and try again..
        /// </summary>
        public static string WARN_NOT_ALL_FIELDS_FILLED {
            get {
                return ResourceManager.GetString("WARN_NOT_ALL_FIELDS_FILLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required setting value(s) cannot be empty. Changes rejected. Fill in the all required setting values and click  &lt;Save&gt; to continue..
        /// </summary>
        public static string WARN_PARAMETERS_ARE_NOT_SAVED {
            get {
                return ResourceManager.GetString("WARN_PARAMETERS_ARE_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment &lt;{0}&gt; cannot be updated due to its Status. Please correct the shipment manually..
        /// </summary>
        public static string WARN_SHIPMENT_IS_CONFIRMED_AND_CANNOT_BE_UPDATED {
            get {
                return ResourceManager.GetString("WARN_SHIPMENT_IS_CONFIRMED_AND_CANNOT_BE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process the Shipment &lt;{0}&gt;. Shipments without packages can be processed only if the &quot;BOX&quot; Box ID is configured.
        /// </summary>
        public static string WARN_SHIPMENT_VALIDATION_BOX {
            get {
                return ResourceManager.GetString("WARN_SHIPMENT_VALIDATION_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process the Shipment &lt;{0}&gt;. Only the shipments with the &quot;Open&quot; status can be processed..
        /// </summary>
        public static string WARN_SHIPMENT_VALIDATION_OPEN {
            get {
                return ResourceManager.GetString("WARN_SHIPMENT_VALIDATION_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process the Shipment &lt;{0}&gt;. Only the shipments with the &quot;Shipment&quot; type can be processed..
        /// </summary>
        public static string WARN_SHIPMENT_VALIDATION_TYPE {
            get {
                return ResourceManager.GetString("WARN_SHIPMENT_VALIDATION_TYPE", resourceCulture);
            }
        }
    }
}
