//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShipment.Settings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorldShipTD")]
        public string UpsProcessName {
            get {
                return ((string)(this["UpsProcessName"]));
            }
            set {
                this["UpsProcessName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpsExportFilePath {
            get {
                return ((string)(this["UpsExportFilePath"]));
            }
            set {
                this["UpsExportFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FedEx.Gsm.Cafe.ApplicationEngine.Gui")]
        public string FedexProcessName {
            get {
                return ((string)(this["FedexProcessName"]));
            }
            set {
                this["FedexProcessName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FedexExportFilePath {
            get {
                return ((string)(this["FedexExportFilePath"]));
            }
            set {
                this["FedexExportFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string AcumaticaLogin {
            get {
                return ((string)(this["AcumaticaLogin"]));
            }
            set {
                this["AcumaticaLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string AcumaticaPassword {
            get {
                return ((string)(this["AcumaticaPassword"]));
            }
            set {
                this["AcumaticaPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AcumaticaCompany {
            get {
                return ((string)(this["AcumaticaCompany"]));
            }
            set {
                this["AcumaticaCompany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool AcumaticaConfirmShipment {
            get {
                return ((bool)(this["AcumaticaConfirmShipment"]));
            }
            set {
                this["AcumaticaConfirmShipment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool UpsAddUpdateAddressBook {
            get {
                return ((bool)(this["UpsAddUpdateAddressBook"]));
            }
            set {
                this["UpsAddUpdateAddressBook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool FedexAddUpdateAddressBook {
            get {
                return ((bool)(this["FedexAddUpdateAddressBook"]));
            }
            set {
                this["FedexAddUpdateAddressBook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/entity/Default/6.00.001")]
        public string AcumaticaSoapDataEndPoint {
            get {
                return ((string)(this["AcumaticaSoapDataEndPoint"]));
            }
            set {
                this["AcumaticaSoapDataEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/entity/auth/login")]
        public string AcumaticaSoapLoginEndPoint {
            get {
                return ((string)(this["AcumaticaSoapLoginEndPoint"]));
            }
            set {
                this["AcumaticaSoapLoginEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AcumaticaBaseUrl {
            get {
                return ((string)(this["AcumaticaBaseUrl"]));
            }
            set {
                this["AcumaticaBaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GeneralApplicationStartPositionTop {
            get {
                return ((int)(this["GeneralApplicationStartPositionTop"]));
            }
            set {
                this["GeneralApplicationStartPositionTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GeneralApplicationStartPositionLeft {
            get {
                return ((int)(this["GeneralApplicationStartPositionLeft"]));
            }
            set {
                this["GeneralApplicationStartPositionLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SmartShipment.Settings.SettingsProvider.SmartShipmentSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AcumaticaDefaultBoxId {
            get {
                return ((string)(this["AcumaticaDefaultBoxId"]));
            }
            set {
                this["AcumaticaDefaultBoxId"] = value;
            }
        }
    }
}
